name: Android CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'renovate.json'
      - '.editorconfig'
      - '.gitignore'
      - '.github/**'
      - '.github/workflows/**'
      - '.idea/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'renovate.json'
      - '.editorconfig'
      - '.gitignore'
      - '.github/**'
      - '.github/workflows/**'
      - '.idea/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{!startsWith(github.event.head_commit.message, '[skip ci]') && success() && github.ref == 'refs/heads/main'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Decode keystore
        run: |
          mkdir -p app
          echo "$KEYSTORE_B64" | base64 -d > app/ono.jks
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build signed Release
        run: |
          ./gradlew assembleRelease \
            -PKEYSTORE_FILE=ono.jks \
            -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            -PKEY_ALIAS=key0 \
            -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }} \
            --warning-mode all --stacktrace
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: ono-release-apk
          path: app/build/outputs/apk/release/**/*.apk

  upload-telegram:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: ono-release-apk
          path: artifacts

      - name: Find APK file
        id: find_apk
        run: |
          apk=$(ls artifacts/*.apk)
          echo "apk_path=$apk" >> $GITHUB_OUTPUT

      - name: Send APK via Telegram API
        env:
          BOT_TOKEN:   ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:     ${{ secrets.TELEGRAM_CHAT_ID }}
          APK_PATH:    ${{ steps.find_apk.outputs.apk_path }}
          SHA:         ${{ github.sha }}
          COMMIT_MSG:  ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          REPO:        ${{ github.repository }}
        run: |
          echo "Sending $APK_PATH"
          
          commit_msg="$COMMIT_MSG"
          commit_author="$COMMIT_AUTHOR"
          commit_url="https://github.com/${REPO}/commit/${SHA}"
          
          caption="🎉 *检测到新的 GitHub 推送！*
          *Commit SHA:* \`${SHA}\`
          
          \`\`\`
          ${commit_msg}
          \`\`\`
          
          *提交者* \`${commit_author}\`
          [查看详情](${commit_url})"
          
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument" \
            -F chat_id="${CHAT_ID}" \
            -F document=@"${APK_PATH}" \
            -F caption="${caption}" \
            -F parse_mode=Markdown
